services:
  - type: web
    name: space-legacy
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://soubzhmklygqtefgqcll.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvdWJ6aG1rbHlncXRlZmdxY2xsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3OTQ2NzQsImV4cCI6MjA3MDM3MDY3NH0.BIXlYUJ3XdhfN5P61D8ksnmnGcmKsl2Ir_1cUwDLRZg
      - key: NODE_ENV
        value: production